module.exports.representatives =[{"SN":1,"STATE":"Abia","SURNAME":"Abonta","OTHERNAMES":"Uzoma Nkem","FEDERALCONSTITUENCY":"Ukwa East/West","PARTY":"PDP","MOBILE":"08032650531","MAILADDRESS":""},
{"SN":2,"STATE":"Abia","SURNAME":"Ndukwe","OTHERNAMES":"Uko Nkole","FEDERALCONSTITUENCY":"Arochukwu/Ohafia","PARTY":"PDP","MOBILE":"08033360305","MAILADDRESS":"aalheritage@yahoo.com"},
{"SN":3,"STATE":"Abia","SURNAME":"Ehiriodo","OTHERNAMES":"Ossy Prestige Chinedu","FEDERALCONSTITUENCY":"Aba North/South","PARTY":"APGA","MOBILE":"","MAILADDRESS":""},
{"SN":4,"STATE":"Abia","SURNAME":"Onuigbo","OTHERNAMES":"Sam","FEDERALCONSTITUENCY":"Umuahia North/South/ Ikwuano","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":5,"STATE":"Abia","SURNAME":"Nwokocha","OTHERNAMES":"Darlington","FEDERALCONSTITUENCY":"Isialangwa North/South","PARTY":"PDP","MOBILE":"0703069666","MAILADDRESS":"nwokochadarlington@gmail.com"},
{"SN":6,"STATE":"Abia","SURNAME":"Onyejeocha","OTHERNAMES":"Nkiruka","FEDERALCONSTITUENCY":"Isuikwuato/Umunneochi","PARTY":"PDP","MOBILE":"08033307519","MAILADDRESS":"Nkey_bobo@yahoo.co.uk"},
{"SN":7,"STATE":"Abia","SURNAME":"Adaelu","OTHERNAMES":"SolomoN Ezinwa","FEDERALCONSTITUENCY":"Obingwa/Ugwunabo/ Osisioma","PARTY":"PDP","MOBILE":"08023145668","MAILADDRESS":""},
{"SN":8,"STATE":"Abia","SURNAME":"Ukeje","OTHERNAMES":"Nnenna Ijeoma ","FEDERALCONSTITUENCY":"Bende","PARTY":"PDP","MOBILE":"08023145668","MAILADDRESS":""},
{"SN":9,"STATE":"Adamawa","SURNAME":"Garba","OTHERNAMES":"Lawal Abubakar","FEDERALCONSTITUENCY":"Yola North/South/Girel","PARTY":"APC","MOBILE":"08036142211","MAILADDRESS":"lgabubakar@yahoo.com"},
{"SN":10,"STATE":"Adamawa","SURNAME":"Namdas","OTHERNAMES":"Abdulrazak Saad","FEDERALCONSTITUENCY":"Mayo Belwa/Ganye/Jada/ Toungo","PARTY":"APC","MOBILE":"07034724818","MAILADDRESS":"theviewernewspaper@yaho o.com"},
{"SN":11,"STATE":"Adamawa","SURNAME":"Yakub","OTHERNAMES":"Yusuf Buba","FEDERALCONSTITUENCY":"Gombi/Hong","PARTY":"APC","MOBILE":"08033145856","MAILADDRESS":"yubyven@yahoo.com"},
{"SN":12,"STATE":"Adamawa","SURNAME":"Kamale","OTHERNAMES":"Adamu Dau Usman","FEDERALCONSTITUENCY":"Madagali/Michika","PARTY":" PDP","MOBILE":"08033145856","MAILADDRESS":""},
{"SN":13,"STATE":"Adamawa","SURNAME":"Laori","OTHERNAMES":"Kwamoti Bitrus","FEDERALCONSTITUENCY":"Demsa/Numan/Lamurde","PARTY":"SDP","MOBILE":"08033145856","MAILADDRESS":""},
{"SN":14,"STATE":"Adamawa","SURNAME":"Gutuwa","OTHERNAMES":"Philip","FEDERALCONSTITUENCY":"Guyuk/Shelleng","PARTY":"APC","MOBILE":"08036168357","MAILADDRESS":"0"},
{"SN":15,"STATE":"Adamawa","SURNAME":"Ibrahim","OTHERNAMES":"Sadiq","FEDERALCONSTITUENCY":"Fufore/Song","PARTY":"APC","MOBILE":"08037010915","MAILADDRESS":"0"},
{"SN":16,"STATE":"Adamawa","SURNAME":"Abubakar","OTHERNAMES":"Abdulrahman Shuaibu","FEDERALCONSTITUENCY":"Miaha/Mubi North/Mubi South","PARTY":"APC","MOBILE":"8064757591","MAILADDRESS":"avasng@yahoo.com"},
{"SN":17,"STATE":"AkwaIbom","SURNAME":"Ekpoatai","OTHERNAMES":"Iwoidighe","FEDERALCONSTITUENCY":"Eket/Onna/Esit Eket/Ibeno","PARTY":"PDP","MOBILE":"08066061001","MAILADDRESS":"oiekpoattai@gmail.com"},
{"SN":18,"STATE":"AkwaIbom","SURNAME":"Okon","OTHERNAMES":"Samuel","FEDERALCONSTITUENCY":"Etinan/Nsit Ibom/Nsit Ubium","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":19,"STATE":"AkwaIbom","SURNAME":"Ekanem","OTHERNAMES":"Boro Asuquo","FEDERALCONSTITUENCY":"Ini/Ikono","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":20,"STATE":"AkwaIbom","SURNAME":"Archibong","OTHERNAMES":"Henry Okon","FEDERALCONSTITUENCY":"Itu/Ibiono Ibom","PARTY":"PDP","MOBILE":"08037055929","MAILADDRESS":"archieokon@yahoo.com"},
{"SN":21,"STATE":"AkwaIbom","SURNAME":"Enyong","OTHERNAMES":"Michael Okon","FEDERALCONSTITUENCY":"Uyo/Uruan/Nsit Atai/IbesikpoAsutan","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":22,"STATE":"AkwaIbom","SURNAME":"Isaac","OTHERNAMES":"Ukotte Emmanuel","FEDERALCONSTITUENCY":"Ukanafun/Oruk Anam","PARTY":"PDP","MOBILE":"08023559082","MAILADDRESS":"ukoete@yahoo.com"},
{"SN":23,"STATE":"AkwaIbom","SURNAME":"Ekon","OTHERNAMES":"Emmanuel","FEDERALCONSTITUENCY":"Abak/Etim Ekpo/Ika","PARTY":"PDP","MOBILE":"07064350430","MAILADDRESS":"emmaekon@yahoo.com"},
{"SN":24,"STATE":"AkwaIbom","SURNAME":"Akpan","OTHERNAMES":"Emmanuel","FEDERALCONSTITUENCY":"Ikot Ekpene/Essien/EssienUdim/Obot Akara","PARTY":"PDP","MOBILE":"08063924548","MAILADDRESS":"emmanuelakpanshiro@mail.com"},
{"SN":25,"STATE":"AkwaIbom","SURNAME":"Uduyork","OTHERNAMES":"Francis Charles","FEDERALCONSTITUENCY":"Ikot Abasi/Mkpat Enin/Eastern","PARTY":"PDP","MOBILE":"08027215258","MAILADDRESS":"Francis_uduyok@yahoo.com"},
{"SN":26,"STATE":"AkwaIbom","SURNAME":"Ekpenyong","OTHERNAMES":"Nse Bassey","FEDERALCONSTITUENCY":"Oron/Mbo/Okobo/ UdungUko/Urue Offong/Oruko","PARTY":"PDP","MOBILE":"08035515526","MAILADDRESS":"nseEkpenyong@yahoo.com"},
{"SN":27,"STATE":"Anambra","SURNAME":"Obiano","OTHERNAMES":"Madubueze Peter","FEDERALCONSTITUENCY":"Anambra East/West","PARTY":"APGA","MOBILE":"08033303928","MAILADDRESS":"pmadubueze@gmail.com"},
{"SN":28,"STATE":"Anambra","SURNAME":"Azodo","OTHERNAMES":"Eucharia Okwunna","FEDERALCONSTITUENCY":"Aguata","PARTY":"PDP","MOBILE":"08033250765","MAILADDRESS":"azodoeucharia@yahoo.com"},
{"SN":29,"STATE":"Anambra","SURNAME":"Azubogu","OTHERNAMES":"Emeka Chris","FEDERALCONSTITUENCY":"Nnewi North/South/Ekwusigo","PARTY":"PDP","MOBILE":"08033380404","MAILADDRESS":"azodoeucharia@yahoo.com"},
{"SN":30,"STATE":"Anambra","SURNAME":"Anohu","OTHERNAMES":"Chukwuemeka","FEDERALCONSTITUENCY":"Ihiala","PARTY":"PDP","MOBILE":"07033046897","MAILADDRESS":"emekaanohu@hotmail.com"},
{"SN":31,"STATE":"Anambra","SURNAME":"Obiajuru","OTHERNAMES":"Idu Emeka Godwin","FEDERALCONSTITUENCY":"Onitsha North/South","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":32,"STATE":"Anambra","SURNAME":"Eze","OTHERNAMES":"Okechukwu Nnamdi","FEDERALCONSTITUENCY":"Aniocha/Njikoka/ Dunukofia","PARTY":"PDP","MOBILE":"08034070573","MAILADDRESS":"droneze@yahoo.co.uk"},
{"SN":33,"STATE":"Anambra","SURNAME":"Obi","OTHERNAMES":"Uche Ifeoma","FEDERALCONSTITUENCY":"Orumba North/South","PARTY":"PDP","MOBILE":"*","MAILADDRESS":""},
{"SN":34,"STATE":"Anambra","SURNAME":"Nnebe","OTHERNAMES":"Anayo","FEDERALCONSTITUENCY":"Awka North/South","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":35,"STATE":"Anambra","SURNAME":"Onyenwife","OTHERNAMES":"Gabriel","FEDERALCONSTITUENCY":"Ayamelun/Oyi","PARTY":"APGA","MOBILE":"08122222743","MAILADDRESS":"gonyenwife@yahoo.com"},
{"SN":36,"STATE":"Anambra","SURNAME":"Chidoka","OTHERNAMES":"Obinna","FEDERALCONSTITUENCY":"Idemili North/South","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":37,"STATE":"Anambra","SURNAME":"Chukwuka","OTHERNAMES":"Onyema Wilfred","FEDERALCONSTITUENCY":"Ogbaru","PARTY":"PDP","MOBILE":"08034023992","MAILADDRESS":"chuboski@hotmail.com"},
{"SN":38,"STATE":"Bauchi","SURNAME":"Dogara","OTHERNAMES":"Yakubu Barry","FEDERALCONSTITUENCY":"Bogoro/Dass/Tafawa Balewa","PARTY":"APC","MOBILE":"07031115847","MAILADDRESS":"doyakubu@gmail.com"},
{"SN":39,"STATE":"Bauchi","SURNAME":"Musa","OTHERNAMES":"Shehu Aliyu","FEDERALCONSTITUENCY":"Bauchi","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":40,"STATE":"Bauchi","SURNAME":"Gololo","OTHERNAMES":"Mohammed Garba","FEDERALCONSTITUENCY":"Gamawa","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":41,"STATE":"Bauchi","SURNAME":"Gurai","OTHERNAMES":"Adamu Alhaji","FEDERALCONSTITUENCY":"Shira/Giade","PARTY":"APC","MOBILE":"08033696324/08025495560","MAILADDRESS":"achiasha@gmail.com"},
{"SN":42,"STATE":"Bauchi","SURNAME":"Yarima","OTHERNAMES":"Ahmed","FEDERALCONSTITUENCY":"Misau/Dambam","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":43,"STATE":"Bauchi","SURNAME":"Mohammed","OTHERNAMES":"Isa Hassan","FEDERALCONSTITUENCY":"Jamare/Itas-Gadau","PARTY":"APC","MOBILE":"08033330448/08059017690","MAILADDRESS":""},
{"SN":44,"STATE":"Bauchi","SURNAME":"Omar","OTHERNAMES":"Tata","FEDERALCONSTITUENCY":"Zaki","PARTY":"APC","MOBILE":"08035860679","MAILADDRESS":"tataomars@gmail.com"},
{"SN":45,"STATE":"Bauchi","SURNAME":"Ningi","OTHERNAMES":"Salisu Zakari","FEDERALCONSTITUENCY":"Ningi/Warji","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":46,"STATE":"Bauchi","SURNAME":"Jika","OTHERNAMES":"Haliru Dauda","FEDERALCONSTITUENCY":"Darazo/Ganjuwa","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":47,"STATE":"Bauchi","SURNAME":"Baba","OTHERNAMES":"Ibrahim Mohammed","FEDERALCONSTITUENCY":"Katagum","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":48,"STATE":"Bauchi","SURNAME":"Gumau","OTHERNAMES":"Lawan Yahaya","FEDERALCONSTITUENCY":"Toro","PARTY":"APC","MOBILE":"08058031250","MAILADDRESS":"lawalyahaya001@yahoo.com"},
{"SN":49,"STATE":"Bauchi","SURNAME":"Abdu","OTHERNAMES":"Mohammed Sani","FEDERALCONSTITUENCY":"Alkaleri/Kirfi","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":50,"STATE":"Bayelsa","SURNAME":"Agbedi","OTHERNAMES":"Fredrick","FEDERALCONSTITUENCY":"Ekeremor/Sagbama","PARTY":"PDP","MOBILE":"08164873547","MAILADDRESS":"gbengbeuk@yahoo.com"},
{"SN":51,"STATE":"Bayelsa","SURNAME":"Foingha","OTHERNAMES":"Jephthah","FEDERALCONSTITUENCY":"Brass/Nembe","PARTY":"PDP","MOBILE":"08037732453","MAILADDRESS":"jfoingha@yahoo.com"},
{"SN":52,"STATE":"Bayelsa","SURNAME":"Ofongo","OTHERNAMES":"Daniel Henry","FEDERALCONSTITUENCY":"Southern Ijaw","PARTY":"PDP","MOBILE":"08037899755","MAILADDRESS":""},
{"SN":53,"STATE":"Bayelsa","SURNAME":"Omoni","OTHERNAMES":"Sodaguno Festus","FEDERALCONSTITUENCY":"Ogbia","PARTY":"PDP","MOBILE":"0706207232/08053720525","MAILADDRESS":"adegafestus@gmail.com"},
{"SN":54,"STATE":"Bayelsa","SURNAME":"Douye","OTHERNAMES":"Diri","FEDERALCONSTITUENCY":"Yenagoa/Kolokuma/Opokuma","PARTY":"PDP","MOBILE":"08036668698","MAILADDRESS":"douyediri@gmail.com"},
{"SN":55,"STATE":"Benue","SURNAME":"Wayo","OTHERNAMES":"Benjamin Orembed","FEDERALCONSTITUENCY":"Kwande/Ushongo","PARTY":"APC","MOBILE":"0802054459/07067663382","MAILADDRESS":"wayoakumeandco@yahoo.c om"},
{"SN":56,"STATE":"Benue","SURNAME":"Adaji","OTHERNAMES":"Ezekiel","FEDERALCONSTITUENCY":"Ohimini/Otukpo","PARTY":"PDP","MOBILE":"08065431936","MAILADDRESS":"0"},
{"SN":57,"STATE":"Benue","SURNAME":"Gbillah","OTHERNAMES":"Mark Terseer","FEDERALCONSTITUENCY":"Gwer East/West","PARTY":"APC","MOBILE":"0802222492408033241479","MAILADDRESS":"markterseer@yahoo.com"},
{"SN":58,"STATE":"Benue","SURNAME":"Abah","OTHERNAMES":"Christian Adabah","FEDERALCONSTITUENCY":"Ado/Ogbadibo/Okpokwu","PARTY":"PDP","MOBILE":"08035906730","MAILADDRESS":"chris@scantnig.com"},
{"SN":59,"STATE":"Benue","SURNAME":"Dyegh","OTHERNAMES":"John","FEDERALCONSTITUENCY":"Gboko/Tarka","PARTY":"APC","MOBILE":"08036808985","MAILADDRESS":"johndyegh@yahoo.com"},
{"SN":60,"STATE":"Benue","SURNAME":"Entonu","OTHERNAMES":"Adamu  Ochepo","FEDERALCONSTITUENCY":"Apa/Agatu","PARTY":"PDP","MOBILE":"08053120382/07060449425","MAILADDRESS":""},
{"SN":61,"STATE":"Benue","SURNAME":"Hembe","OTHERNAMES":"Iorwase Herman","FEDERALCONSTITUENCY":"Konshisha/Vandekiya","PARTY":"APC","MOBILE":"08033035100","MAILADDRESS":"hembrix@yahoo.com"},
{"SN":62,"STATE":"Benue","SURNAME":"Dominic","OTHERNAMES":"Dickson Tarkighir","FEDERALCONSTITUENCY":"Makurdi/Guma","PARTY":"APC","MOBILE":"08036063554","MAILADDRESS":"farkiir@yahoo.com"},
{"SN":63,"STATE":"Benue","SURNAME":"Okwu","OTHERNAMES":"Samson","FEDERALCONSTITUENCY":"Obi/Oju","PARTY":"PDP","MOBILE":"08033205109","MAILADDRESS":""},
{"SN":64,"STATE":"Benue","SURNAME":"Udende","OTHERNAMES":"Emmanuel","FEDERALCONSTITUENCY":"Katsina Ala/Logo/Ukum","PARTY":"PDP","MOBILE":"08036111345","MAILADDRESS":""},
{"SN":65,"STATE":"Benue","SURNAME":"Yisa","OTHERNAMES":"Emmanuel Orker-Jev","FEDERALCONSTITUENCY":"Buruku","PARTY":"APC","MOBILE":"08026366750","MAILADDRESS":"eyisajev63@gmail.com"},
{"SN":66,"STATE":"Borno","SURNAME":"Rahis","OTHERNAMES":"Kadiri","FEDERALCONSTITUENCY":"Maiduguri (Metropolitan)","PARTY":"APC","MOBILE":"8067055559","MAILADDRESS":"AbdulKadirRahis@gmail.com"},
{"SN":67,"STATE":"Borno","SURNAME":"Bashir","OTHERNAMES":"Asabe Vilita","FEDERALCONSTITUENCY":"Damboa/Gwoza/Chibok","PARTY":"APC","MOBILE":"7030603617","MAILADDRESS":"ambello228@yahoo.com"},
{"SN":68,"STATE":"Borno","SURNAME":"Bello","OTHERNAMES":"Ayuba Mohammed","FEDERALCONSTITUENCY":"Jere","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":69,"STATE":"Borno","SURNAME":"Gana","OTHERNAMES":"Bukar","FEDERALCONSTITUENCY":"Kukawa/Mobbar/ Abadam/ Guzamalai","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":70,"STATE":"Borno","SURNAME":"Maina","OTHERNAMES":"Muhmud Lawan","FEDERALCONSTITUENCY":"Dikwa/Mafat/Konduga","PARTY":"APC","MOBILE":"08034944630","MAILADDRESS":"Hon.mlmaina@yahoo.co.uk"},
{"SN":71,"STATE":"Borno","SURNAME":"Muktar","OTHERNAMES":"Betara Aliyu","FEDERALCONSTITUENCY":"Biu/Bayo/Shani/Kwaya Kusar","PARTY":"APC","MOBILE":"07034022555","MAILADDRESS":"amuktarbetara@yahoo.com"},
{"SN":72,"STATE":"Borno","SURNAME":"Monguno","OTHERNAMES":"Mohammed Tahir","FEDERALCONSTITUENCY":"Monguno/Marte/Nganzai","PARTY":"APC","MOBILE":"07053173540","MAILADDRESS":"mtmonguno@gmail.com"},
{"SN":73,"STATE":"Borno","SURNAME":"Satumari","OTHERNAMES":"Jibrin","FEDERALCONSTITUENCY":"Askira-Uba/Hawul","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":74,"STATE":"Borno","SURNAME":"Ngamdu","OTHERNAMES":"Mohammed  Sanda","FEDERALCONSTITUENCY":"Kaga/Gubio/Magumeri","PARTY":"APC","MOBILE":"08034409966","MAILADDRESS":"masngamdu@yahoo.com"},
{"SN":75,"STATE":"Borno","SURNAME":"Sherrif","OTHERNAMES":"Mohammed Nur","FEDERALCONSTITUENCY":"Bama/Ngala/Kalabalge","PARTY":"APC","MOBILE":"08062217118","MAILADDRESS":"mnsngala@hotmail.com"},
{"SN":76,"STATE":"CrossRiver","SURNAME":"Idabo","OTHERNAMES":"Legor","FEDERALCONSTITUENCY":"Obanliku/Obudu/ Bakwarra","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":77,"STATE":"CrossRiver","SURNAME":"Asuquo","OTHERNAMES":"Daniel Effiom","FEDERALCONSTITUENCY":"Akamkpa/Biase","PARTY":"PDP","MOBILE":"08038066505/08029029958","MAILADDRESS":"asuquodaniel08@yahoo.com"},
{"SN":78,"STATE":"CrossRiver","SURNAME":"Ayi","OTHERNAMES":"Essien Ekpenyong","FEDERALCONSTITUENCY":"Calabar South/Akpabuyo / Bekwarra","PARTY":"PDP","MOBILE":"08033486856","MAILADDRESS":""},
{"SN":79,"STATE":"CrossRiver","SURNAME":"Etiaba","OTHERNAMES":"Michael","FEDERALCONSTITUENCY":"Obubra/Etung","PARTY":"PDP","MOBILE":"08066882463","MAILADDRESS":"goodfutureltd@gmail.com"},
{"SN":80,"STATE":"CrossRiver","SURNAME":"Agibe","OTHERNAMES":"Chris Ngoro","FEDERALCONSTITUENCY":"Boki/Ikom","PARTY":"PDP","MOBILE":"08098381832","MAILADDRESS":"chris.agibe@gmail.com"},
{"SN":81,"STATE":"CrossRiver","SURNAME":"Ewa","OTHERNAMES":"Bassey Eko","FEDERALCONSTITUENCY":"Yakurr/Abi","PARTY":"PDP","MOBILE":"08077761111","MAILADDRESS":""},
{"SN":82,"STATE":"CrossRiver","SURNAME":"Agom","OTHERNAMES":"Jarigbe","FEDERALCONSTITUENCY":"Ogoja/Yala","PARTY":"PDP","MOBILE":"08065276817","MAILADDRESS":"jarrigom@yahoo.com"},
{"SN":83,"STATE":"CrossRiver","SURNAME":"Mbora","OTHERNAMES":"Eta","FEDERALCONSTITUENCY":"Calabar Municipal/ Odukpani","PARTY":"PDP","MOBILE":"08033651271","MAILADDRESS":"h.etambora@yahoo.com"},
{"SN":84,"STATE":"Delta","SURNAME":"Idisi","OTHERNAMES":"Lovette","FEDERALCONSTITUENCY":"Ethiope East/West","PARTY":"PDP","MOBILE":"08062940611","MAILADDRESS":"lovette.idis@lonestardrillin g-ng.com"},
{"SN":85,"STATE":"Delta","SURNAME":"Mrakpor","OTHERNAMES":"Onyemaechi Joan","FEDERALCONSTITUENCY":"Aniocha North/South OshimiliNorth/South","PARTY":"PDP","MOBILE":"08037126394","MAILADDRESS":"Davidfavourtriplets@yahoo.com"},
{"SN":86,"STATE":"Delta","SURNAME":"Pondi","OTHERNAMES":"Julius","FEDERALCONSTITUENCY":"Burutu","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":87,"STATE":"Delta","SURNAME":"Ossai","OTHERNAMES":"Nicholas","FEDERALCONSTITUENCY":"Ndokwa East/West/ Ukwuani","PARTY":"PDP","MOBILE":"08037009085","MAILADDRESS":""},
{"SN":88,"STATE":"Delta","SURNAME":"Mutu","OTHERNAMES":"Nicholas Ebomo","FEDERALCONSTITUENCY":"Bomadi/Patani","PARTY":"PDP","MOBILE":"07052200000/08035433727","MAILADDRESS":""},
{"SN":89,"STATE":"Delta","SURNAME":"Nwokolo","OTHERNAMES":"Victor Onyemaechi","FEDERALCONSTITUENCY":"Ika North/South","PARTY":"PDP","MOBILE":"08036496981/08033151030","MAILADDRESS":""},
{"SN":90,"STATE":"Delta","SURNAME":"Ahwinahwi","OTHERNAMES":"Solomon","FEDERALCONSTITUENCY":"Ughelli North/South/Udu","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":91,"STATE":"Delta","SURNAME":"Ogor","OTHERNAMES":"Leonard Ukuweh","FEDERALCONSTITUENCY":"Isoko North/South","PARTY":"PDP","MOBILE":"08037169858","MAILADDRESS":"okuwdi@yahoo.com"},
{"SN":92,"STATE":"Delta","SURNAME":"Oboro","OTHERNAMES":"Evelyn","FEDERALCONSTITUENCY":"Okpe/Sapele/Uvwie","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":93,"STATE":"Delta","SURNAME":"Reyenieju","OTHERNAMES":"Daniel OritseGbubemi","FEDERALCONSTITUENCY":"Warri North/South/West","PARTY":"PDP","MOBILE":"08056012991","MAILADDRESS":""},
{"SN":94,"STATE":"Ebonyi","SURNAME":"Nwazunku","OTHERNAMES":"Chukwuma","FEDERALCONSTITUENCY":"Ebonyi/Ohaukwu","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":95,"STATE":"Ebonyi","SURNAME":"Edwin","OTHERNAMES":"Anayo","FEDERALCONSTITUENCY":"Ezza North/Ishielu","PARTY":"PDP","MOBILE":"08037087271","MAILADDRESS":"anatexresources@yahoo.com"},
{"SN":96,"STATE":"Ebonyi","SURNAME":"Igariwey","OTHERNAMES":"Iduma Enwo","FEDERALCONSTITUENCY":"Afikpo North/South","PARTY":"PDP","MOBILE":"8033334323","MAILADDRESS":"s.ogbaga@gmail.com"},
{"SN":97,"STATE":"Ebonyi","SURNAME":"Ogbaba","OTHERNAMES":"Sylvester","FEDERALCONSTITUENCY":"Abakiliki/Izzi","PARTY":"PDP","MOBILE":"8065319759","MAILADDRESS":"s.ogbaga@gmail.com"},
{"SN":98,"STATE":"Ebonyi","SURNAME":"Okorie","OTHERNAMES":"Linus","FEDERALCONSTITUENCY":"Ivo/Ohaozara/Onicha","PARTY":"PDP","MOBILE":"7034511773","MAILADDRESS":""},
{"SN":99,"STATE":"Ebonyi","SURNAME":"Ogbee","OTHERNAMES":"Laz","FEDERALCONSTITUENCY":"Ikwo/Ezza South","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":100,"STATE":"Edo","SURNAME":"Agbonayinma","OTHERNAMES":"E. Johnson","FEDERALCONSTITUENCY":"Egor Ikpoba Okha","PARTY":"PDP","MOBILE":"08059297797","MAILADDRESS":"texoil@usa.com"},
{"SN":101,"STATE":"Edo","SURNAME":"Akpatason","OTHERNAMES":"Peter Ohia Zojeh","FEDERALCONSTITUENCY":"Akoko-Edo","PARTY":"APC","MOBILE":"08037403122","MAILADDRESS":"pakpatason@gmail.com"},
{"SN":102,"STATE":"Edo","SURNAME":"Edionwele","OTHERNAMES":"Joseph","FEDERALCONSTITUENCY":"Esan Central/West/ Igueben","PARTY":"PDP","MOBILE":"08035420939","MAILADDRESS":"Joeedionwele@yahoo.com"},
{"SN":103,"STATE":"Edo","SURNAME":"Iriase","OTHERNAMES":"Pally","FEDERALCONSTITUENCY":"Owan East/West","PARTY":"APC","MOBILE":"08035401925","MAILADDRESS":"pallyiriase@yahoo.com"},
{"SN":104,"STATE":"Edo","SURNAME":"Ogun","OTHERNAMES":"Sergius Oseasochie","FEDERALCONSTITUENCY":"Esan North-East/South-East","PARTY":"PDP","MOBILE":"08033055951","MAILADDRESS":"sergiusoke@yahoo.com"},
{"SN":105,"STATE":"Edo","SURNAME":"Shaibu","OTHERNAMES":"Philip","FEDERALCONSTITUENCY":"Etsako East/West Central","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":106,"STATE":"Edo","SURNAME":"Ogbeide- Ihama","OTHERNAMES":"Omoregie","FEDERALCONSTITUENCY":"Oredo","PARTY":"PDP","MOBILE":"*","MAILADDRESS":""},
{"SN":107,"STATE":"Edo","SURNAME":"Aisowerien","OTHERNAMES":"Patrick","FEDERALCONSTITUENCY":"Orhionmwon uhunmwode","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":108,"STATE":"Edo","SURNAME":"Igbinedion","OTHERNAMES":"Omosode Gabriella(Ms)","FEDERALCONSTITUENCY":"Ovia North-East/South-West","PARTY":"PDP","MOBILE":"08092777111","MAILADDRESS":"omosede2015@gmail.com"},
{"SN":109,"STATE":"Ekiti","SURNAME":"Agboola","OTHERNAMES":"Kehinde Emmanuel","FEDERALCONSTITUENCY":"Ikole/Oye North","PARTY":"PDP","MOBILE":"08037869042","MAILADDRESS":"agboolakennedy@yahoo.com"},
{"SN":110,"STATE":"Ekiti","SURNAME":"Aina","OTHERNAMES":"Thaddeous","FEDERALCONSTITUENCY":"Moba/Lejemeje/Ido Osi","PARTY":"PDP","MOBILE":"08168255154","MAILADDRESS":"akin270809@yahoo.com"},
{"SN":111,"STATE":"Ekiti","SURNAME":"Adekola","OTHERNAMES":"Segun Alex","FEDERALCONSTITUENCY":"Ekiti South-West/ Ikere/Orun/ Ise","PARTY":"PDP","MOBILE":"08033182304","MAILADDRESS":"Alex_segunadekola@yahoo. com"},
{"SN":112,"STATE":"Ekiti","SURNAME":"Awodumila","OTHERNAMES":"Akinyele Julius","FEDERALCONSTITUENCY":"Emure/Gbonyin/Ekiti East","PARTY":"PDP","MOBILE":"08038601707","MAILADDRESS":"akinawodumila@yahoo.com"},
{"SN":113,"STATE":"Ekiti","SURNAME":"Oladimeji","OTHERNAMES":"Ayodele","FEDERALCONSTITUENCY":"Ado-Ekiti/Irepodun/ Ifelodun","PARTY":"PDP","MOBILE":"08034045757","MAILADDRESS":"ayodeleola2001@yahoo.com"},
{"SN":114,"STATE":"Ekiti","SURNAME":"Oni","OTHERNAMES":"Olamide Johnson","FEDERALCONSTITUENCY":"Ijero/Ekiti-West/Efon","PARTY":"PDP","MOBILE":"08033092609","MAILADDRESS":"Oni4real2008@yahoo.com"},
{"SN":115,"STATE":"Enugu","SURNAME":"Ugwuegede","OTHERNAMES":"Ikechukwu","FEDERALCONSTITUENCY":"Nsukka/Igboeze South","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":116,"STATE":"Enugu","SURNAME":"Ebenyi","OTHERNAMES":"Kingsley .S.","FEDERALCONSTITUENCY":"Enugu East/Isi-Uzo","PARTY":"PDP","MOBILE":"08065505591/08088875122","MAILADDRESS":""},
{"SN":117,"STATE":"Enugu","SURNAME":"Ikechukwu","OTHERNAMES":"Toby","FEDERALCONSTITUENCY":"Aninri/Agwu/Oji-Uzo","PARTY":"PDP","MOBILE":"08033141949","MAILADDRESS":""},
{"SN":118,"STATE":"Enugu","SURNAME":"Ngwu","OTHERNAMES":"Stella .U.O.","FEDERALCONSTITUENCY":"Igbo-Etiti/Uzo-Uwani","PARTY":"PDP","MOBILE":"08034677971","MAILADDRESS":""},
{"SN":119,"STATE":"Enugu","SURNAME":"Ujam","OTHERNAMES":"Chukwuemeka","FEDERALCONSTITUENCY":"Nkanu East/West","PARTY":"PDP","MOBILE":"07036798995","MAILADDRESS":"emekaujam@hotmail.com"},
{"SN":120,"STATE":"Enugu","SURNAME":"Oji","OTHERNAMES":"Chime","FEDERALCONSTITUENCY":"Enugu North/Enugu South","PARTY":"PDP","MOBILE":"08033385508","MAILADDRESS":"0"},
{"SN":121,"STATE":"Enugu","SURNAME":"Amadi","OTHERNAMES":"Dennis Oguerinwa","FEDERALCONSTITUENCY":"Ezeagu/Udi","PARTY":"PDP","MOBILE":"08033201402","MAILADDRESS":"amadiogu@yahoo.com"},
{"SN":122,"STATE":"Enugu","SURNAME":"Agbo","OTHERNAMES":"Dennis Nnamdi","FEDERALCONSTITUENCY":"Igboeze North/Udenu","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":123,"STATE":"FCT","SURNAME":"Zakari","OTHERNAMES":"Angulu","FEDERALCONSTITUENCY":"Abaji/Gwalgwalada/Kuje/ Kwali","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":124,"STATE":"FCT","SURNAME":"Zephaniah","OTHERNAMES":"Jisalo Bitrus","FEDERALCONSTITUENCY":"AMAC/Bwari","PARTY":"PDP","MOBILE":"08033498130","MAILADDRESS":""},
{"SN":125,"STATE":"Gombe","SURNAME":"Abubakar","OTHERNAMES":"Yinusa Ahmad","FEDERALCONSTITUENCY":"Yamaltu/Debba","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":126,"STATE":"Gombe","SURNAME":"Kawawa","OTHERNAMES":"Barambu Umaru","FEDERALCONSTITUENCY":"Akko","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":127,"STATE":"Gombe","SURNAME":"Bello","OTHERNAMES":"Binta","FEDERALCONSTITUENCY":"Kaltungo/Shongom","PARTY":"PDP","MOBILE":"08070614592/08089880373","MAILADDRESS":""},
{"SN":128,"STATE":"Gombe","SURNAME":"Ali","OTHERNAMES":"Isa J.C","FEDERALCONSTITUENCY":"Balanga/Biliri","PARTY":"PDP","MOBILE":"08074000085","MAILADDRESS":"Isanass@yahoo.com"},
{"SN":129,"STATE":"Gombe","SURNAME":"Tongo","OTHERNAMES":"Yaya Bauchi","FEDERALCONSTITUENCY":"Kwami/Funakaye/Gombe","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":130,"STATE":"Gombe","SURNAME":"Dukku","OTHERNAMES":"Aishatu Jibril","FEDERALCONSTITUENCY":"Dukku/Nafada","PARTY":"APC","MOBILE":"08037039464","MAILADDRESS":"ajdukku25@gmail.com"},
{"SN":131,"STATE":"Imo","SURNAME":"Alagboso","OTHERNAMES":"Jerry","FEDERALCONSTITUENCY":"Orlu/Orsu/Oru East","PARTY":"PDP","MOBILE":"08033098677/08098203993","MAILADDRESS":"jyagbaso@yahoo.com"},
{"SN":132,"STATE":"Imo","SURNAME":"Nwauba","OTHERNAMES":"Henry Ugochukwu","FEDERALCONSTITUENCY":"Mbaitoli/Ikeduru","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":133,"STATE":"Imo","SURNAME":"Igbokwe","OTHERNAMES":"Raphael .N.","FEDERALCONSTITUENCY":"Ahiazu Mbaise/Ezinihitte","PARTY":"PDP","MOBILE":"07039095929","MAILADDRESS":""},
{"SN":134,"STATE":"Imo","SURNAME":"Eke","OTHERNAMES":"Bede Uchenna","FEDERALCONSTITUENCY":"Abor Mbaise/Ngor Okpala","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":135,"STATE":"Imo","SURNAME":"Opia","OTHERNAMES":"Goodluck Nana","FEDERALCONSTITUENCY":"Ohaji/Egbema/Oguta/ OruWest","PARTY":"PDP","MOBILE":"08066248878","MAILADDRESS":"goodluckopiah@yahoo.com"},
{"SN":136,"STATE":"Imo","SURNAME":"Chukwukere","OTHERNAMES":"Austine Ikechukwu","FEDERALCONSTITUENCY":"Ideato North/South","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":137,"STATE":"Imo","SURNAME":"Onwuabuariri","OTHERNAMES":"Obinna Kingsley","FEDERALCONSTITUENCY":"Onuimo/Okigwe/Isiala Mbano","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":138,"STATE":"Imo","SURNAME":"Onyereri","OTHERNAMES":"Chukwudi VictorJones","FEDERALCONSTITUENCY":"Nkwerre/Isu/Nwangele/Njaba","PARTY":"PDP","MOBILE":"08033125450/08053284919","MAILADDRESS":"jones.onyereri@gmail.com"},
{"SN":139,"STATE":"Imo","SURNAME":"Onyewuchi","OTHERNAMES":"Ezenwa Francis","FEDERALCONSTITUENCY":"Owerri Municipal/North/ West","PARTY":"PDP","MOBILE":"08099454012/08032012132","MAILADDRESS":"ezeonyewuchi@gmail.com"},
{"SN":140,"STATE":"Imo","SURNAME":"Okafor","OTHERNAMES":"Chike John","FEDERALCONSTITUENCY":"Ehime Mbano/Ihitte Uboma/ Obowo","PARTY":"APC","MOBILE":"08033269174","MAILADDRESS":"chike.jokafor@gmail.com"},
{"SN":141,"STATE":"Jigawa","SURNAME":"Abubakar","OTHERNAMES":"Hassan Fulata","FEDERALCONSTITUENCY":"Birniwa/Guri/Kiri-Kasamma","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":142,"STATE":"Jigawa","SURNAME":"Kazaure","OTHERNAMES":"Muhammed Gudaji","FEDERALCONSTITUENCY":"Kazaure/Roni/Gwiwa/ Yankashi","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":143,"STATE":"Jigawa","SURNAME":"Kila","OTHERNAMES":"Yuguda Hassan","FEDERALCONSTITUENCY":"Gwaram","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":144,"STATE":"Jigawa","SURNAME":"Dutse","OTHERNAMES":"Ibrahim Abdullahi","FEDERALCONSTITUENCY":"Dutse/Kiyawa","PARTY":"APC","MOBILE":"08033110090","MAILADDRESS":"naibawa@yahoo.com"},
{"SN":145,"STATE":"Jigawa","SURNAME":"Usman","OTHERNAMES":"Ibrahim Auyo","FEDERALCONSTITUENCY":"Hadejia/Auyo/Kafin Hausa","PARTY":"APC","MOBILE":"08033158082","MAILADDRESS":"abdulluhigeje@yahoo.com"},
{"SN":146,"STATE":"Jigawa","SURNAME":"Zorro","OTHERNAMES":"Muhammad Sani","FEDERALCONSTITUENCY":"Gagarawa/Gumel/Mai Gatari","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":147,"STATE":"Jigawa","SURNAME":"Saidu","OTHERNAMES":"Yusuf Miga","FEDERALCONSTITUENCY":"Jahun/Miga","PARTY":"APC","MOBILE":"07031076452","MAILADDRESS":"saidumiga@yahoo.com"},
{"SN":148,"STATE":"Jigawa","SURNAME":"Aliyu","OTHERNAMES":"Magaji Dau","FEDERALCONSTITUENCY":"Birnin-Kudu/Buji","PARTY":"APC","MOBILE":"07038230002","MAILADDRESS":"datty02@gmail.com"},
{"SN":149,"STATE":"Jigawa","SURNAME":"Muhammad","OTHERNAMES":"Gausu Boyi","FEDERALCONSTITUENCY":"Ringim/Taura","PARTY":"APC","MOBILE":"08032615535","MAILADDRESS":"gausuringim@gmail.com"},
{"SN":150,"STATE":"Jigawa","SURNAME":"Gawo","OTHERNAMES":"Muhammed AdamuFagen","FEDERALCONSTITUENCY":"Babura/Garki","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":151,"STATE":"Jigawa","SURNAME":"Kaugama","OTHERNAMES":"Rabiu Garba","FEDERALCONSTITUENCY":"Mallam Madori/Kaugama","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":152,"STATE":"Kaduna","SURNAME":"Soba","OTHERNAMES":"Muhammad Musa","FEDERALCONSTITUENCY":"Soba","PARTY":"APC","MOBILE":"08033113371","MAILADDRESS":"Mohammedsoba77@gmail.c om"},
{"SN":153,"STATE":"Kaduna","SURNAME":"Arabo","OTHERNAMES":"Simon Yakubu","FEDERALCONSTITUENCY":"Kauru","PARTY":"PDP","MOBILE":"08022067414","MAILADDRESS":"arabosimon@yahoo.com"},
{"SN":154,"STATE":"Kaduna","SURNAME":"Usman","OTHERNAMES":"Mohammed","FEDERALCONSTITUENCY":"Makarfi/Kudan","PARTY":"APC","MOBILE":"08099009030","MAILADDRESS":"mlusman2011@gmail.com"},
{"SN":155,"STATE":"Kaduna","SURNAME":"Bala","OTHERNAMES":"Yusuf","FEDERALCONSTITUENCY":"Ikara/Kubau","PARTY":"APC","MOBILE":"08091699345","MAILADDRESS":"yusufbala172@yahoo.com"},
{"SN":156,"STATE":"Kaduna","SURNAME":"Barde","OTHERNAMES":"Umar Yakubu","FEDERALCONSTITUENCY":"Kajuru/Chikun","PARTY":"PDP","MOBILE":"08035768320","MAILADDRESS":""},
{"SN":157,"STATE":"Kaduna","SURNAME":"Suleiman","OTHERNAMES":"Samaila Sani","FEDERALCONSTITUENCY":"Kaduna North","PARTY":"APC","MOBILE":"08098000626","MAILADDRESS":"samailasuleiman@yahoo.com"},
{"SN":158,"STATE":"Kaduna","SURNAME":"Muhammed","OTHERNAMES":"Abubakar","FEDERALCONSTITUENCY":"Igabi","PARTY":"APC","MOBILE":"07035681585","MAILADDRESS":""},
{"SN":159,"STATE":"Kaduna","SURNAME":"Chanchangi","OTHERNAMES":"Rufai Ahmed","FEDERALCONSTITUENCY":"Kaduna South","PARTY":"APC","MOBILE":"08069783748","MAILADDRESS":"rufaichanchangi@gmail.com"},
{"SN":160,"STATE":"Kaduna","SURNAME":"Katung","OTHERNAMES":"Sunday Marshal","FEDERALCONSTITUENCY":"Jaba/Zangon Kataf","PARTY":"PDP","MOBILE":"08094446444","MAILADDRESS":"sunnyside22002@yahoo.com"},
{"SN":161,"STATE":"Kaduna","SURNAME":"Garba","OTHERNAMES":"Shehu Nicholas","FEDERALCONSTITUENCY":"Jemaa/Sanga","PARTY":"PDP","MOBILE":"08037138793","MAILADDRESS":"sngarba@gmail.com"},
{"SN":162,"STATE":"Kaduna","SURNAME":"Gwani","OTHERNAMES":"Gideon Lucas","FEDERALCONSTITUENCY":"Kaura","PARTY":"PDP","MOBILE":"7083913110","MAILADDRESS":"gideongwani@yahoo.com"},
{"SN":163,"STATE":"Kaduna","SURNAME":"Rabiu","OTHERNAMES":"Lawal Muhammed","FEDERALCONSTITUENCY":"Lere","PARTY":"APC","MOBILE":"08033499022","MAILADDRESS":"0"},
{"SN":164,"STATE":"Kaduna","SURNAME":"Jagaba","OTHERNAMES":"Jagaba Adams","FEDERALCONSTITUENCY":"Kachia/Kagarko","PARTY":"APC","MOBILE":"08055870828","MAILADDRESS":"jagba.adams@yahoo.com"},
{"SN":165,"STATE":"Kaduna","SURNAME":"Muhammed","OTHERNAMES":"Garba Datti","FEDERALCONSTITUENCY":"Sabon Gari","PARTY":"APC","MOBILE":"08183156886","MAILADDRESS":"dattigarba@gmail.com"},
{"SN":166,"STATE":"Kaduna","SURNAME":"Shekarau","OTHERNAMES":"Hassan Adamu","FEDERALCONSTITUENCY":"Birnin/Gwari/Giwa","PARTY":"APC","MOBILE":"08051197079","MAILADDRESS":"hassanadamushekarau@gmail.com"},
{"SN":167,"STATE":"Kaduna","SURNAME":"Tajudeen","OTHERNAMES":"Abbas","FEDERALCONSTITUENCY":"Zaria","PARTY":"APC","MOBILE":"08037052227","MAILADDRESS":"tajudeenabbas@yahoo.com"},
{"SN":168,"STATE":"Kano","SURNAME":"Abdulkadir","OTHERNAMES":"Tijani Jobe","FEDERALCONSTITUENCY":"Dawakin Tofa/Tofa/RiminGado","PARTY":"APC","MOBILE":"08036210294","MAILADDRESS":""},
{"SN":169,"STATE":"Kano","SURNAME":"Bala","OTHERNAMES":"Sani Umar","FEDERALCONSTITUENCY":"Tsanyawa/Kunchi","PARTY":"APC","MOBILE":"08036166400","MAILADDRESS":"engr.sani@yahoo.com"},
{"SN":170,"STATE":"Kano","SURNAME":"Gaya","OTHERNAMES":"Abdullahi Mahmud","FEDERALCONSTITUENCY":"Albasu/Gaya/Ajingi","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":171,"STATE":"Kano","SURNAME":"Ado","OTHERNAMES":"Musa","FEDERALCONSTITUENCY":"Gezawa/Gabasawa","PARTY":"APC","MOBILE":"08023605733","MAILADDRESS":"musaado24@yahoo.com"},
{"SN":172,"STATE":"Kano","SURNAME":"Ahmed","OTHERNAMES":"Nasiru Ali","FEDERALCONSTITUENCY":"Nassarawa","PARTY":"APC","MOBILE":"08037866602","MAILADDRESS":"mciinternational@yahoo.com"},
{"SN":173,"STATE":"Kano","SURNAME":"Aliyu","OTHERNAMES":"Sani Mohammed","FEDERALCONSTITUENCY":"Rano/Bunkure/Kibiya","PARTY":"APC","MOBILE":"08131924065/08036515090","MAILADDRESS":"sanimohammedrano@gmail.com"},
{"SN":174,"STATE":"Kano","SURNAME":"Baballe","OTHERNAMES":"Bashir","FEDERALCONSTITUENCY":"Minjibir/Ungogo","PARTY":"APC","MOBILE":"08036043754","MAILADDRESS":"bashirballe@yahoo.com"},
{"SN":175,"STATE":"Kano","SURNAME":"Dan’agundi","OTHERNAMES":"Manir Babba","FEDERALCONSTITUENCY":"Kumbotso","PARTY":"APC","MOBILE":"08089265355/08034297696","MAILADDRESS":"munirbabba@yahoo.com"},
{"SN":176,"STATE":"Kano","SURNAME":"Ayuba","OTHERNAMES":"Badamasi","FEDERALCONSTITUENCY":"Dambatta/Makoda","PARTY":"APC","MOBILE":"08033173788","MAILADDRESS":"badamasayuba@yahoo.com"},
{"SN":177,"STATE":"Kano","SURNAME":"Dawaki","OTHERNAMES":"Mustapha Bala","FEDERALCONSTITUENCY":"Dawakin Kudu/Warawa","PARTY":"APC","MOBILE":"07034945594/07084775848","MAILADDRESS":"dawak12@yahoo.com"},
{"SN":178,"STATE":"Kano","SURNAME":"Mohammed","OTHERNAMES":"Garba Ibrahim","FEDERALCONSTITUENCY":"Gwale","PARTY":"APC","MOBILE":"08033262108","MAILADDRESS":"mig25ng@yahoo.com"},
{"SN":179,"STATE":"Kano","SURNAME":"Garba","OTHERNAMES":"Alhassan Ado Doguwa","FEDERALCONSTITUENCY":"Doguwa/Tundun Wada","PARTY":"APC","MOBILE":"08034502986","MAILADDRESS":"alhassandoguwa01@yahoo. com"},
{"SN":180,"STATE":"Kano","SURNAME":"Garo","OTHERNAMES":"Sule Nasiru","FEDERALCONSTITUENCY":"Gwarzo/Ikabo","PARTY":"APC","MOBILE":"08078099850","MAILADDRESS":"nsgaro@yahoo.com"},
{"SN":181,"STATE":"Kano","SURNAME":"Ilah","OTHERNAMES":"Nasiru Baballe","FEDERALCONSTITUENCY":"Tarauni","PARTY":"APC","MOBILE":"08037011938","MAILADDRESS":"nasirubaballe@yahoo.com"},
{"SN":182,"STATE":"Kano","SURNAME":"Jibrin","OTHERNAMES":"Abdulmunim","FEDERALCONSTITUENCY":"Bebeji/Kiru","PARTY":"APC","MOBILE":"08036130007/08059669181","MAILADDRESS":"Abdulmumunijibrin.houseo freps@yahoo.com"},
{"SN":183,"STATE":"Kano","SURNAME":"Umar","OTHERNAMES":"Garba","FEDERALCONSTITUENCY":"Sumaila/Takai","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":184,"STATE":"Kano","SURNAME":"Romo ","OTHERNAMES":"Sulaiman Aliyu","FEDERALCONSTITUENCY":"Shanono/Bagwai","PARTY":"APC","MOBILE":"08035942398","MAILADDRESS":"Sulaimanaied@gmail.com"},
{"SN":185,"STATE":"Kano","SURNAME":"Bichi","OTHERNAMES":" Ahmed Garba ","FEDERALCONSTITUENCY":"Bichi","PARTY":"APC","MOBILE":"08037864934","MAILADDRESS":"aliyumadaki@yahoo.com"},
{"SN":186,"STATE":"Kano","SURNAME":"Madaki","OTHERNAMES":"Aliyu Sani","FEDERALCONSTITUENCY":"Dala","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":187,"STATE":"Kano","SURNAME":"Mukhtari","OTHERNAMES":"MohammedChiromawa","FEDERALCONSTITUENCY":"Kura/Madobi/Garun Mallam","PARTY":"APC","MOBILE":"08023098655","MAILADDRESS":"mun@yahoo.com"},
{"SN":188,"STATE":"Kano","SURNAME":"Danburam","OTHERNAMES":"Abubukar Nuhu","FEDERALCONSTITUENCY":"Municipal","PARTY":"APC","MOBILE":"08033163954","MAILADDRESS":"abubakarnuhu@hotmail.com"},
{"SN":189,"STATE":"Kano","SURNAME":"Suleiman","OTHERNAMES":"Aminu","FEDERALCONSTITUENCY":"Fagge","PARTY":"APC","MOBILE":"08028451370/08037016357","MAILADDRESS":"Aminusule007@yahoo.com"},
{"SN":190,"STATE":"Kano","SURNAME":"Wudil","OTHERNAMES":"Ali Muhammed","FEDERALCONSTITUENCY":"Wudil/Garko","PARTY":"APC","MOBILE":"08172890700/08052590915","MAILADDRESS":"aliwudil@gmail.com"},
{"SN":191,"STATE":"Kano","SURNAME":"Aliyu","OTHERNAMES":"Shehu Usman","FEDERALCONSTITUENCY":"Karaye/Rogo","PARTY":"APC","MOBILE":"08089104606","MAILADDRESS":"usenimedi@yahoo.com"},
{"SN":192,"STATE":"Katsina","SURNAME":"Mani","OTHERNAMES":"Aminu Ashiru","FEDERALCONSTITUENCY":"Bindawa/Mani","PARTY":"APC","MOBILE":"08085555277","MAILADDRESS":"honaminu@gmail.com"},
{"SN":193,"STATE":"Katsina","SURNAME":"Shaaibu","OTHERNAMES":"Kabir","FEDERALCONSTITUENCY":"Batagarawa/Charanchi/ Rimi","PARTY":"APC","MOBILE":"08035988749","MAILADDRESS":""},
{"SN":194,"STATE":"Katsina","SURNAME":"Mohammed","OTHERNAMES":"Muntari Dandutse","FEDERALCONSTITUENCY":"Dandume/Funtua","PARTY":"APC","MOBILE":"08098303742/08187556014","MAILADDRESS":"M.Dandutse@gmail.com"},
{"SN":195,"STATE":"Katsina","SURNAME":"Suleiman","OTHERNAMES":"Salisu Salisco","FEDERALCONSTITUENCY":"Jibia/Kaita","PARTY":"APC","MOBILE":"08035904484/09090608860","MAILADDRESS":"sssalisco@yahoo.com suleimansalisco77@gmail.c om"},
{"SN":196,"STATE":"Katsina","SURNAME":"Daura","OTHERNAMES":"Nasiru Sani Zangon","FEDERALCONSTITUENCY":"Baure/Zango","PARTY":"APC","MOBILE":"08037024015","MAILADDRESS":"nazdaura@yahoo.com"},
{"SN":197,"STATE":"Katsina","SURNAME":"Mashi","OTHERNAMES":"Sani Bello","FEDERALCONSTITUENCY":"Dutsi/Mashi","PARTY":"APC","MOBILE":"08037456563","MAILADDRESS":"sabema374@gmail.com"},
{"SN":198,"STATE":"Katsina","SURNAME":"Murtala","OTHERNAMES":"Ibrahim Danmazari","FEDERALCONSTITUENCY":"Matazu/Musawa","PARTY":"APC","MOBILE":"08099999070","MAILADDRESS":"almatazu@yahoo.com"},
{"SN":199,"STATE":"Katsina","SURNAME":"Ibrahim","OTHERNAMES":"Babangida","FEDERALCONSTITUENCY":"Kafur/Malumfashi","PARTY":"APC","MOBILE":"08142467450","MAILADDRESS":"ibmahuta@gmail.com"},
{"SN":200,"STATE":"Katsina","SURNAME":"Isah","OTHERNAMES":"Murtala","FEDERALCONSTITUENCY":"Faskari/Kankara Sabuwa","PARTY":"APC","MOBILE":"08033963487/08036432442","MAILADDRESS":"murtalaisah@gmail.com"},
{"SN":201,"STATE":"Katsina","SURNAME":"Fago","OTHERNAMES":"Sani Saidu","FEDERALCONSTITUENCY":"Daura/Mai’adua Sandamu","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":202,"STATE":"Katsina","SURNAME":"Safana","OTHERNAMES":"Ahmed Dayyabu","FEDERALCONSTITUENCY":"Batsari/Dan-Musa/Safana","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":203,"STATE":"Katsina","SURNAME":"Kaita","OTHERNAMES":"Ahmed Usman Babba","FEDERALCONSTITUENCY":"Kankia/Ingawa/Kusada","PARTY":"APC","MOBILE":"07081888802/08032554883","MAILADDRESS":"babbahmed@yahoo.com"},
{"SN":204,"STATE":"Katsina","SURNAME":"Kurfi","OTHERNAMES":"Danlami Mohammed","FEDERALCONSTITUENCY":"Dutsin-Ma/Kurfi","PARTY":"APC","MOBILE":"08033330623","MAILADDRESS":"danlami.kurfi@gmail.com"},
{"SN":205,"STATE":"Katsina","SURNAME":"Tukur","OTHERNAMES":"Amiruuddin","FEDERALCONSTITUENCY":"Bakori/Danja","PARTY":"APC","MOBILE":"08092199990/08035616445","MAILADDRESS":"amirutukuridris@yahoo.com"},
{"SN":206,"STATE":"Katsina","SURNAME":"Abubakar","OTHERNAMES":"Sheik Umar","FEDERALCONSTITUENCY":"Katsina Central","PARTY":"APC","MOBILE":"08033138096","MAILADDRESS":"sheikumarabubakar@gmail. com"},
{"SN":207,"STATE":"Kebbi","SURNAME":"Danladi","OTHERNAMES":"Aliyu","FEDERALCONSTITUENCY":"Zuru/Faka/Sakaba/D/Wasagu","PARTY":"APC","MOBILE":"08135332179","MAILADDRESS":"0"},
{"SN":208,"STATE":"Kebbi","SURNAME":"Jega","OTHERNAMES":"Mohammed Umar","FEDERALCONSTITUENCY":"Gwandu/Aliero/Jega","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":209,"STATE":"Kebbi","SURNAME":"Mohammed","OTHERNAMES":"Munir Uthman","FEDERALCONSTITUENCY":"Argungu/Augie","PARTY":"APC","MOBILE":"08032310768","MAILADDRESS":"argungu2@yahoo.co.uk"},
{"SN":210,"STATE":"Kebbi","SURNAME":"Faruk","OTHERNAMES":"Abdullahi Umar","FEDERALCONSTITUENCY":"B/Kebbi/Kalgo/Bunza","PARTY":"APC","MOBILE":"08036619955","MAILADDRESS":"abdulfaruk44@yahoo.com"},
{"SN":211,"STATE":"Kebbi","SURNAME":"Kangiwa","OTHERNAMES":"Husseini Sulaiman","FEDERALCONSTITUENCY":"Arewa/Dandi","PARTY":"APC","MOBILE":"07031011111","MAILADDRESS":"0"},
{"SN":212,"STATE":"Kebbi","SURNAME":"Suru","OTHERNAMES":"Abdullahi Hassan","FEDERALCONSTITUENCY":"Bagodu/Suru","PARTY":"APC","MOBILE":"08065628818","MAILADDRESS":"0"},
{"SN":213,"STATE":"Kebbi","SURNAME":"Koko","OTHERNAMES":"Salisu Garba","FEDERALCONSTITUENCY":"Maiyamu/Koko-Besse","PARTY":"APC","MOBILE":"08033640097","MAILADDRESS":"0"},
{"SN":214,"STATE":"Kebbi","SURNAME":"Dantani","OTHERNAMES":"Mohammed","FEDERALCONSTITUENCY":"Yauri/Shanga/Ngaski","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":215,"STATE":"Kogi","SURNAME":"Ajanah","OTHERNAMES":"Muhammed Kabir","FEDERALCONSTITUENCY":"Adavi/Okehi","PARTY":"APC","MOBILE":"08092770042","MAILADDRESS":"mkajanah@yahoo.com"},
{"SN":216,"STATE":"Kogi","SURNAME":"Egwu","OTHERNAMES":"Emanual M","FEDERALCONSTITUENCY":"Idah/Igalamela/Ibaji/Ofu","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":217,"STATE":"Kogi","SURNAME":"Jibril","OTHERNAMES":"Umar Buba","FEDERALCONSTITUENCY":"Lokoja/Kogi (KK)","PARTY":"APC","MOBILE":"08036009559","MAILADDRESS":"umarjibril57@gmail.com"},
{"SN":218,"STATE":"Kogi","SURNAME":"Karimi","OTHERNAMES":"Sunday Steve","FEDERALCONSTITUENCY":"Yagba East/West/ Mopamuro","PARTY":"PDP","MOBILE":"08033146617","MAILADDRESS":"karimisunday@yahoo.com"},
{"SN":219,"STATE":"Kogi","SURNAME":"Omale","OTHERNAMES":"Hassan Atayoma","FEDERALCONSTITUENCY":"Ankpa/Omala/Olamaboro","PARTY":"APC","MOBILE":"08033146617","MAILADDRESS":"karimisunday@yahoo.com"},
{"SN":220,"STATE":"Kogi","SURNAME":"Idrisu","OTHERNAMES":"Lawal Muhammadu","FEDERALCONSTITUENCY":"Ajaokuta","PARTY":"APC","MOBILE":"08035874288","MAILADDRESS":"Lawalidirisu7@yahoo.com"},
{"SN":221,"STATE":"Kogi","SURNAME":"Tajudeen","OTHERNAMES":"Yusuf Ayo","FEDERALCONSTITUENCY":"Ijumu/Kabba/Bunu","PARTY":"PDP","MOBILE":"08062443690","MAILADDRESS":"Yu suftj2003@yahoo.com"},
{"SN":222,"STATE":"Kogi","SURNAME":"Bello","OTHERNAMES":"Abdullahi","FEDERALCONSTITUENCY":"Okene/Ogori-Magogo","PARTY":"APC","MOBILE":"08036210534","MAILADDRESS":"onoruoyizabello@yahoo.com"},
{"SN":223,"STATE":"Kogi","SURNAME":"Okolo","OTHERNAMES":"Benjamin Ikani","FEDERALCONSTITUENCY":"Bassa/Dekina","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":224,"STATE":"Kwara","SURNAME":"Garba","OTHERNAMES":"Abubakar Kaninike","FEDERALCONSTITUENCY":"Ilorin East/South","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":225,"STATE":"Kwara","SURNAME":"Adedoyin","OTHERNAMES":"Funke (Princess)","FEDERALCONSTITUENCY":"Ekiti/Isin/Irepodun/Oke-Ero","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":226,"STATE":"Kwara","SURNAME":"Ahman-pategi","OTHERNAMES":"Aliyu","FEDERALCONSTITUENCY":"Edu/Moro/Patigi","PARTY":"APC","MOBILE":"08059960606","MAILADDRESS":"aliyuahmanpategi@yahoo.com"},
{"SN":227,"STATE":"Kwara","SURNAME":"Mohammed","OTHERNAMES":"Zakari","FEDERALCONSTITUENCY":"Baruten/Kaima","PARTY":"APC","MOBILE":"08050756905","MAILADDRESS":"Lafiaf70@yahoo.com"},
{"SN":228,"STATE":"Kwara","SURNAME":"Atunwa","OTHERNAMES":"Rasak Olatunde","FEDERALCONSTITUENCY":"Ilorin West/Asa","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":229,"STATE":"Kwara","SURNAME":"Olayonu","OTHERNAMES":"Tope Olarinoye","FEDERALCONSTITUENCY":"Ifelodun/Offa/Oyun","PARTY":"APC","MOBILE":"08094848004","MAILADDRESS":"olayonutope@yahoo.com"},
{"SN":230,"STATE":"Lagos","SURNAME":"Abiodun","OTHERNAMES":"Faleke James","FEDERALCONSTITUENCY":"Ikeja","PARTY":"APC","MOBILE":"08033069103","MAILADDRESS":"jamesfaleke.jf@gmail.com"},
{"SN":231,"STATE":"Lagos","SURNAME":"Adaranijo","OTHERNAMES":"Taofik Abiodun","FEDERALCONSTITUENCY":"Agege","PARTY":"APC","MOBILE":"08058581200","MAILADDRESS":"taadaranijo@gmail.com"},
{"SN":232,"STATE":"Lagos","SURNAME":"Orji","OTHERNAMES":"Rita (Mrs)","FEDERALCONSTITUENCY":"Ajeromi-Ifelodun","PARTY":"PDP","MOBILE":"08033213348","MAILADDRESS":"Ritaodichimma@gmail.com growthinwomen@yahoo.com"},
{"SN":233,"STATE":"Lagos","SURNAME":"AAdebanjo","OTHERNAMES":"Oluwafemi Bandele","FEDERALCONSTITUENCY":"Alimosho","PARTY":"APC","MOBILE":"09036366666","MAILADDRESS":""},
{"SN":234,"STATE":"Lagos","SURNAME":"Ayodeji","OTHERNAMES":"Joseph Adebayo","FEDERALCONSTITUENCY":"Apapa","PARTY":"APC","MOBILE":"08100800000","MAILADDRESS":""},
{"SN":235,"STATE":"Lagos","SURNAME":"Shadimu","OTHERNAMES":"Mutiu","FEDERALCONSTITUENCY":"Oshodi-Isolo 1","PARTY":"PDP","MOBILE":"08023023052","MAILADDRESS":"mutiushadimu@gmail.com"},
{"SN":236,"STATE":"Lagos","SURNAME":"Akinloye","OTHERNAMES":"Babajide Hazeez","FEDERALCONSTITUENCY":"Eti-Osa","PARTY":"APC","MOBILE":"08051993743/08024624743","MAILADDRESS":"jideakinloye@yahoo.com"},
{"SN":237,"STATE":"Lagos","SURNAME":"Abdulkabir","OTHERNAMES":"Abayomi Ayeola","FEDERALCONSTITUENCY":"Ijebu-Lekki","PARTY":"APC","MOBILE":"08180954390","MAILADDRESS":"0"},
{"SN":238,"STATE":"Lagos","SURNAME":"Olatunji","OTHERNAMES":"Soyinka","FEDERALCONSTITUENCY":"Surulere II","PARTY":"PDP","MOBILE":"08023044250","MAILADDRESS":"Olasho2015@gmail.com"},
{"SN":239,"STATE":"Lagos","SURNAME":"Agunsoye","OTHERNAMES":"Oluwarotimi Ojo","FEDERALCONSTITUENCY":"Kosofe","PARTY":"APC","MOBILE":"08033083998","MAILADDRESS":""},
{"SN":240,"STATE":"Lagos","SURNAME":"Benson","OTHERNAMES":"Babajimi Adegoke","FEDERALCONSTITUENCY":"Ikorodu","PARTY":"APC","MOBILE":"08023070541","MAILADDRESS":"Basbenson@gmail.com"},
{"SN":241,"STATE":"Lagos","SURNAME":"Gbajabiamila","OTHERNAMES":"Femi Hakeem","FEDERALCONSTITUENCY":"Surulere I","PARTY":"APC","MOBILE":"08037181508","MAILADDRESS":"femigbaja1@gmail.com"},
{"SN":242,"STATE":"Lagos","SURNAME":"Nwulu","OTHERNAMES":"Tony Chinedu","FEDERALCONSTITUENCY":"Oshodi-Isolo II","PARTY":"PDP","MOBILE":"08063222222","MAILADDRESS":""},
{"SN":243,"STATE":"Lagos","SURNAME":"Ayinla","OTHERNAMES":"Bolaji Yusuf","FEDERALCONSTITUENCY":"Mushin II","PARTY":"APC","MOBILE":"08088054422","MAILADDRESS":"BYA2011@yahoo.com"},
{"SN":244,"STATE":"Lagos","SURNAME":"Obasa","OTHERNAMES":"Tajudeen","FEDERALCONSTITUENCY":"Ojo","PARTY":"PDP","MOBILE":"08189671960","MAILADDRESS":"tajudeenobasa@gmail.com"},
{"SN":245,"STATE":"Lagos","SURNAME":"Diya","OTHERNAMES":"Oyewole Babafemi","FEDERALCONSTITUENCY":"Somolu","PARTY":"APC","MOBILE":"08034754693","MAILADDRESS":""},
{"SN":246,"STATE":"Lagos","SURNAME":"Kako Are","OTHERNAMES":"Abayomi Dauda","FEDERALCONSTITUENCY":"Mushin I","PARTY":"ACCORD","MOBILE":"08033062095","MAILADDRESS":"kakobose@yahoo.com"},
{"SN":247,"STATE":"Lagos","SURNAME":"Tasir","OTHERNAMES":"Olawale Raji","FEDERALCONSTITUENCY":"Epe","PARTY":"APC","MOBILE":"08033327443","MAILADDRESS":"waleraji@hotmail.com"},
{"SN":248,"STATE":"Lagos","SURNAME":"Adewale","OTHERNAMES":"Elijah Oluwatayo","FEDERALCONSTITUENCY":"Ifako-Ijaiye","PARTY":"APC","MOBILE":"08037139315","MAILADDRESS":"oluadewalejah@yahoo.com"},
{"SN":249,"STATE":"Lagos","SURNAME":"Badru","OTHERNAMES":"Dolapo Enitan","FEDERALCONSTITUENCY":"Lagos Island I","PARTY":"APC","MOBILE":"0803075341408051235453","MAILADDRESS":"edolapo@hotmail.com"},
{"SN":250,"STATE":"Lagos","SURNAME":"Egoh","OTHERNAMES":"Oghene Emma","FEDERALCONSTITUENCY":"Amuwo Odofin","PARTY":"PDP","MOBILE":"0803075341408051235453","MAILADDRESS":"edolapo@hotmail.com"},
{"SN":251,"STATE":"Lagos","SURNAME":"Jimoh","OTHERNAMES":"AbdulRaheem Olajide","FEDERALCONSTITUENCY":"Lagos Mainland","PARTY":"APC","MOBILE":"08033019132","MAILADDRESS":"Jjjetgroups@yahoo.com"},
{"SN":252,"STATE":"Lagos","SURNAME":"Bamgbose","OTHERNAMES":"James","FEDERALCONSTITUENCY":"Badagry","PARTY":"APC","MOBILE":"08022232716","MAILADDRESS":"josephbam22@gmail.com"},
{"SN":253,"STATE":"Lagos","SURNAME":"Yakubu","OTHERNAMES":"Abiodun Balogun, Akanni","FEDERALCONSTITUENCY":"Lagos Island II","PARTY":"APC","MOBILE":"08022444422","MAILADDRESS":"eniloloboo15@yahoo.com"},
{"SN":254,"STATE":"Nasarawa","SURNAME":"Baba","OTHERNAMES":"Musa Onwana","FEDERALCONSTITUENCY":"Nasarawa/Toto","PARTY":"APC","MOBILE":"08061245730/08098615338","MAILADDRESS":"musamallammusa@yahoo.c om"},
{"SN":255,"STATE":"Nasarawa","SURNAME":"Dahiru","OTHERNAMES":"Abubakar Sarki","FEDERALCONSTITUENCY":"Lafia/Obi","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":256,"STATE":"Nasarawa","SURNAME":"Gbefwi","OTHERNAMES":"Gaza Jonathan","FEDERALCONSTITUENCY":"Keffi/Karu/Kokona","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":257,"STATE":"Nasarawa","SURNAME":"Ombugadu","OTHERNAMES":"David  Emmanuel","FEDERALCONSTITUENCY":"Akwanga/Nasarawa Eggon/ Wamba","PARTY":"PDP","MOBILE":"08036704090/08167392926","MAILADDRESS":"dave4matics002@yahoo.com"},
{"SN":258,"STATE":"Nasarawa","SURNAME":"Onawo","OTHERNAMES":"Mohammed Ogosi","FEDERALCONSTITUENCY":"Awe/Doma/Keana","PARTY":"PDP","MOBILE":"08096492518/08098195206","MAILADDRESS":"onawom@yahoo.com"},
{"SN":259,"STATE":"Niger","SURNAME":"Abdulahi","OTHERNAMES":"Abubakar Lado","FEDERALCONSTITUENCY":"Gurara/Suleja/Tafa","PARTY":"APC","MOBILE":"08036314405","MAILADDRESS":"Maiallah2015@yahoo.com"},
{"SN":260,"STATE":"Niger","SURNAME":"Nago","OTHERNAMES":"Umar Mohammed","FEDERALCONSTITUENCY":"Chanchaga","PARTY":"APC","MOBILE":"08034532003/08028542003","MAILADDRESS":"mohammedbago@yahoo.com"},
{"SN":261,"STATE":"Niger","SURNAME":"Shadafi","OTHERNAMES":"Salihu Adamu","FEDERALCONSTITUENCY":"Bosso/Paikoro","PARTY":"APC","MOBILE":"08036136085","MAILADDRESS":"shadafi2008@yahoo.com"},
{"SN":262,"STATE":"Niger","SURNAME":"Mahmud","OTHERNAMES":"MohammedAbdulkadir","FEDERALCONSTITUENCY":"Agaie/LapajiKontagora/Wushishi/ Agwara/Borgu","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":263,"STATE":"Niger","SURNAME":"Garba","OTHERNAMES":"Idris Abdullahi","FEDERALCONSTITUENCY":"Kontagora/Wushishi/Mariga/Masheg","PARTY":"APC","MOBILE":"0707777044","MAILADDRESS":"abdulgi@yahoo.com"},
{"SN":264,"STATE":"Niger","SURNAME":"Rofia","OTHERNAMES":"Umar Mohammed","FEDERALCONSTITUENCY":"Agwara/Borgu","PARTY":"APC","MOBILE":"08089880961","MAILADDRESS":""},
{"SN":265,"STATE":"Niger","SURNAME":"Abu","OTHERNAMES":"Ahmed","FEDERALCONSTITUENCY":"Edati/Lavun/Mokwa","PARTY":"APC","MOBILE":"08037726006","MAILADDRESS":"ssiwsgroup@gmail.com"},
{"SN":266,"STATE":"Niger","SURNAME":"Adamu","OTHERNAMES":"Abubakar Chika","FEDERALCONSTITUENCY":"Shiroro/Rafi/Munya","PARTY":"APC","MOBILE":"08035909090","MAILADDRESS":"chikaabubakar@gmail.com"},
{"SN":267,"STATE":"Niger","SURNAME":"Saleh","OTHERNAMES":"Shehu","FEDERALCONSTITUENCY":"Magama/Rijau","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":268,"STATE":"Niger","SURNAME":"Faruk","OTHERNAMES":"Muhammadu Bala","FEDERALCONSTITUENCY":"Katcha/Gbako/Bida","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":269,"STATE":"Ogun","SURNAME":"Abdel-Majid","OTHERNAMES":"Aremo AdekoyaAdesegun","FEDERALCONSTITUENCY":"Ijebu North/East/OgunWaterside","PARTY":"PDP","MOBILE":"08037470021","MAILADDRESS":"attackeradekoya@yahoo.com"},
{"SN":270,"STATE":"Ogun","SURNAME":"Oladele","OTHERNAMES":"Kayode","FEDERALCONSTITUENCY":"Egbado North/Imeko Afon","PARTY":"APC","MOBILE":"08066527289","MAILADDRESS":""},
{"SN":271,"STATE":"Ogun","SURNAME":"Isiaka","OTHERNAMES":"Ayokunle Ibrahim","FEDERALCONSTITUENCY":"Ifo/Ewekoro","PARTY":"APC","MOBILE":"08039390909","MAILADDRESS":"Ib_easy@yahoo.com"},
{"SN":272,"STATE":"Ogun","SURNAME":"Akinlade","OTHERNAMES":"Adekunle Abdulkabir","FEDERALCONSTITUENCY":"Egbado South/Ipokia","PARTY":"APC","MOBILE":"08027126622","MAILADDRESS":"adekunle.akinlade@yahoo. Com"},
{"SN":273,"STATE":"Ogun","SURNAME":"Adebutu","OTHERNAMES":"Oladipupo","FEDERALCONSTITUENCY":"Ileoluji Okeigbo/Odigbo/ Remo North/Sagamu/Ikenne","PARTY":"PDP","MOBILE":"08056166099","MAILADDRESS":"oladipupoadebutu@gmail.com"},
{"SN":274,"STATE":"Ogun","SURNAME":"Odeneye","OTHERNAMES":"Kehinde Olusegun","FEDERALCONSTITUENCY":"Ijebu-Ode/Ijebu North East/ Odogbolu","PARTY":"APC","MOBILE":"07034034847","MAILADDRESS":"kentfola@yahoo.com"},
{"SN":275,"STATE":"Ogun","SURNAME":"Jimoh","OTHERNAMES":"Olusola Ojugbele","FEDERALCONSTITUENCY":"Ado-Odo/Ota","PARTY":"APC","MOBILE":"08033141820","MAILADDRESS":"jimohojugbele@yahoo.co.u k"},
{"SN":276,"STATE":"Ogun","SURNAME":"Kazzim","OTHERNAMES":"Mukaila Olayiwola","FEDERALCONSTITUENCY":"Abeokuta North/Obafemi- Owode/Odeda","PARTY":"APC","MOBILE":"08033039691","MAILADDRESS":"lakazzim@yahoo.com"},
{"SN":277,"STATE":"Ogun","SURNAME":"William","OTHERNAMES":"Olusegun Samuel","FEDERALCONSTITUENCY":"Abeokuta South","PARTY":"APC","MOBILE":"08073397050","MAILADDRESS":"seg4pelvis@yahoo.com"},
{"SN":278,"STATE":"Ondo","SURNAME":"Olowookere","OTHERNAMES":"Afe","FEDERALCONSTITUENCY":"Akure North/South","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":279,"STATE":"Ondo","SURNAME":"Baderinwa","OTHERNAMES":"Bamidele White","FEDERALCONSTITUENCY":"Idanre/Ifedore","PARTY":"APC","MOBILE":"08033235265","MAILADDRESS":""},
{"SN":280,"STATE":"Ondo","SURNAME":"Akinfolarin","OTHERNAMES":"Mayowa Samuel","FEDERALCONSTITUENCY":"Ileoluji-Okeibo/Odigbo","PARTY":"PDP","MOBILE":"08030559857","MAILADDRESS":"akinfolarinmayowasamuel@yahoo.com"},
{"SN":281,"STATE":"Ondo","SURNAME":"Akinlaja","OTHERNAMES":"Joseph","FEDERALCONSTITUENCY":"Ondo South East/West","PARTY":"PDP","MOBILE":"08033078253","MAILADDRESS":""},
{"SN":282,"STATE":"Ondo","SURNAME":"Omogbehin","OTHERNAMES":"Mike Adeniyi (Prince)","FEDERALCONSTITUENCY":"Okitipupa/Irele","PARTY":"PDP","MOBILE":"08033038389","MAILADDRESS":""},
{"SN":283,"STATE":"Ondo","SURNAME":"Kolawole","OTHERNAMES":"Babatunde Gabriel","FEDERALCONSTITUENCY":"Akoko South East/West","PARTY":"APC","MOBILE":"08030781711","MAILADDRESS":"babagabrief2002@yahoo.com"},
{"SN":284,"STATE":"Ondo","SURNAME":"Olemija","OTHERNAMES":"Friday Stephen","FEDERALCONSTITUENCY":"Akoko North East/West","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":285,"STATE":"Ondo","SURNAME":"Akinjo","OTHERNAMES":"Victor Kolade","FEDERALCONSTITUENCY":"Eseodo/Ilaje","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":286,"STATE":"Ondo","SURNAME":"Ayorinde","OTHERNAMES":"Olabode","FEDERALCONSTITUENCY":"Owo/Ose","PARTY":"APC","MOBILE":"08037142677","MAILADDRESS":""},
{"SN":287,"STATE":"Osun","SURNAME":"Oke","OTHERNAMES":"Busayo Oluwole","FEDERALCONSTITUENCY":"Obokun/Oriade","PARTY":"PDP","MOBILE":"08054454444","MAILADDRESS":"woleokeeaoke@gmail.com"},
{"SN":288,"STATE":"Osun","SURNAME":"Alabi","OTHERNAMES":"Mojeed Olujinmi","FEDERALCONSTITUENCY":"Ede North/South/Egbedore/Ejigbo","PARTY":"APC","MOBILE":"08068964365","MAILADDRESS":"mojeed62@yahoo.co.uk"},
{"SN":289,"STATE":"Osun","SURNAME":"Ajayi","OTHERNAMES":"Adeyinka Ayantunki","FEDERALCONSTITUENCY":"Odo-otin/Ifelodun/Boripe","PARTY":"APC","MOBILE":"08033236747","MAILADDRESS":"goldadedayo@gmail.com"},
{"SN":290,"STATE":"Osun","SURNAME":"Ajibola","OTHERNAMES":"Famurewa Israel","FEDERALCONSTITUENCY":"Atakunmosa East/West/ IlesaEast/West","PARTY":"APC","MOBILE":"08033079790","MAILADDRESS":"bolafamurewa@yahoo.com"},
{"SN":291,"STATE":"Osun","SURNAME":"Akintayo","OTHERNAMES":"Gafaru Amere","FEDERALCONSTITUENCY":"Ayedire/Iwo/Ola-Oluwa","PARTY":"APC","MOBILE":"07059646871/08038486553","MAILADDRESS":"gafaketayo2010@yahoo.com"},
{"SN":292,"STATE":"Osun","SURNAME":"Fakeye","OTHERNAMES":"Julius Olufemi","FEDERALCONSTITUENCY":"Boluwaduro/Ifedayo/Ila","PARTY":"APC","MOBILE":"07063098372","MAILADDRESS":"jolufak@yahoo.com"},
{"SN":293,"STATE":"Osun","SURNAME":"Lasun","OTHERNAMES":"Yusuf Sulaimon","FEDERALCONSTITUENCY":"Irepodun/Olorunda/Osogbo/Orolu","PARTY":"APC","MOBILE":"08032109175","MAILADDRESS":"lasunyussuf@gmail.com"},
{"SN":294,"STATE":"Osun","SURNAME":"Adeogun","OTHERNAMES":"Albert Abiodun","FEDERALCONSTITUENCY":"Ife Central/East/North/ South","PARTY":"PDP","MOBILE":"08033268553","MAILADDRESS":"barradeogun@yahoo.com"},
{"SN":295,"STATE":"Osun","SURNAME":"Omidiran","OTHERNAMES":"Ayo Hulayat","FEDERALCONSTITUENCY":"Ayedaade/Irewole/Isokan","PARTY":"APC","MOBILE":"08033050607","MAILADDRESS":"ayomidiran@gmail.com"},
{"SN":296,"STATE":"Oyo","SURNAME":"Abiodun","OTHERNAMES":"Awoleye Dada","FEDERALCONSTITUENCY":"Ibadan North","PARTY":"APC","MOBILE":"08033241610","MAILADDRESS":"abbylinkolu@yahoo.com"},
{"SN":297,"STATE":"Oyo","SURNAME":"Oladele","OTHERNAMES":"Olatunbosun George","FEDERALCONSTITUENCY":"Irepo/Orelope/Olorunsogo","PARTY":"APC","MOBILE":"08125254801","MAILADDRESS":"Shegoa7@gmail.com"},
{"SN":298,"STATE":"Oyo","SURNAME":"Ogunwuyi","OTHERNAMES":"Segun Ebenezer","FEDERALCONSTITUENCY":"Ogbomosho North/South / Oriire","PARTY":"LABOUR","MOBILE":"","MAILADDRESS":""},
{"SN":299,"STATE":"Oyo","SURNAME":"Adepoju","OTHERNAMES":"Sunday Adeyemi","FEDERALCONSTITUENCY":"Ibarapa East/Ido","PARTY":"APC","MOBILE":"08080666751/08033235824","MAILADDRESS":"askadepoju@yahoo.com"},
{"SN":300,"STATE":"Oyo","SURNAME":"Lam-Adesina","OTHERNAMES":"Dapo","FEDERALCONSTITUENCY":"Ibadan North-East/South-East","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":301,"STATE":"Oyo","SURNAME":"Adeyemi","OTHERNAMES":"Akeem (Prince)","FEDERALCONSTITUENCY":"Afijio/Atiba East/Oyo West","PARTY":"APC","MOBILE":"081400005555","MAILADDRESS":""},
{"SN":302,"STATE":"Oyo","SURNAME":"Akintola","OTHERNAMES":"Taiwo Michael","FEDERALCONSTITUENCY":"Egbeda/Ona-Ara","PARTY":"APC","MOBILE":"08030760684","MAILADDRESS":"Idunnuoluwa1965@gmail.c om"},
{"SN":303,"STATE":"Oyo","SURNAME":"Fijabi","OTHERNAMES":"Saheed Akinade","FEDERALCONSTITUENCY":"Ibadan South-West/ North- West","PARTY":"APC","MOBILE":"08073916741*","MAILADDRESS":""},
{"SN":304,"STATE":"Oyo","SURNAME":"Olatunbosun","OTHERNAMES":"Bayo","FEDERALCONSTITUENCY":"Atisbo/Saki East/West","PARTY":"APC","MOBILE":"08037189191","MAILADDRESS":"olatubosunboladale@yahoo.com"},
{"SN":305,"STATE":"Oyo","SURNAME":"Ojoawo","OTHERNAMES":"Olugbenga Ayoade","FEDERALCONSTITUENCY":"Ibarapa Central/North","PARTY":"APC","MOBILE":"08038899207","MAILADDRESS":"ibegadeibarapa@yahoo.com"},
{"SN":306,"STATE":"Oyo","SURNAME":"Olatoye","OTHERNAMES":"Temitope Sugar","FEDERALCONSTITUENCY":"Akinyele/Lagelu","PARTY":"APC","MOBILE":"08033479788","MAILADDRESS":""},
{"SN":307,"STATE":"Oyo","SURNAME":"Odebunmi","OTHERNAMES":"Olusegun Dokun","FEDERALCONSTITUENCY":"Ogo-Oluwa/Surulere","PARTY":"PDP","MOBILE":"07037062535","MAILADDRESS":"s.odebunmi@yahoo.com"},
{"SN":308,"STATE":"Oyo","SURNAME":"Abiodun","OTHERNAMES":"Olasupo Adeola","FEDERALCONSTITUENCY":"Iseyin/Itesiwaju/Kajola/Iwajowa","PARTY":"APC","MOBILE":"08067885400","MAILADDRESS":"abisupo@yahoo.co.uk"},
{"SN":309,"STATE":"Oyo","SURNAME":"Olugbeni","OTHERNAMES":"Samson Olusunbo","FEDERALCONSTITUENCY":"Oluyole","PARTY":"APC","MOBILE":"08165529473","MAILADDRESS":"viewsamma@gmail.com"},
{"SN":310,"STATE":"Plateau","SURNAME":"Idris","OTHERNAMES":"Ahmed","FEDERALCONSTITUENCY":"Wase","PARTY":"APC","MOBILE":"08035920149","MAILADDRESS":"ahmedanemaje@yahoo.com"},
{"SN":311,"STATE":"Plateau","SURNAME":"Kwande","OTHERNAMES":"Suleiman Yahaya","FEDERALCONSTITUENCY":"Bassa/Jos North","PARTY":"APC","MOBILE":"08069460627","MAILADDRESS":""},
{"SN":312,"STATE":"Plateau","SURNAME":"Maren","OTHERNAMES":"Solomon","FEDERALCONSTITUENCY":"Mangu/Bokkos","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":313,"STATE":"Plateau","SURNAME":"Golu","OTHERNAMES":"Timothy","FEDERALCONSTITUENCY":"Paskshin/Kanke/Kanam","PARTY":"PDP","MOBILE":"08033326795","MAILADDRESS":"timotigolu@yahoo.com"},
{"SN":314,"STATE":"Plateau","SURNAME":"Shekarau","OTHERNAMES":"Johnbull","FEDERALCONSTITUENCY":"Shendam/Mikang/Qua'an/pan","PARTY":"PDP","MOBILE":"08037035414","MAILADDRESS":"tiemlong02@yahoo.com"},
{"SN":315,"STATE":"Plateau","SURNAME":"Pwajok","OTHERNAMES":"Edward Gyang","FEDERALCONSTITUENCY":"Jos South/East","PARTY":"PDP","MOBILE":"08056280538","MAILADDRESS":"egpwajok@yahoo.co.uk"},
{"SN":316,"STATE":"Plateau","SURNAME":"Lar","OTHERNAMES":"Beni","FEDERALCONSTITUENCY":"Langtang North/South","PARTY":"PDP","MOBILE":"08069189919","MAILADDRESS":""},
{"SN":317,"STATE":"Plateau","SURNAME":"Gyang","OTHERNAMES":"Istifanus Dung","FEDERALCONSTITUENCY":"Barikinladi/Riyom","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":318,"STATE":"Rivers","SURNAME":"Apiafi","OTHERNAMES":"Betty Okagua","FEDERALCONSTITUENCY":"Ahoada East/Abua/Odual","PARTY":"PDP","MOBILE":"08034070087","MAILADDRESS":""},
{"SN":319,"STATE":"Rivers","SURNAME":"Obi","OTHERNAMES":"Uche Nnam","FEDERALCONSTITUENCY":"Ogba/Egbema/Ndoni/ AhoadaWest","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":320,"STATE":"Rivers","SURNAME":"Chikere","OTHERNAMES":"Kenneth Anayo","FEDERALCONSTITUENCY":"Port Harcourt I","PARTY":"PDP","MOBILE":"08033090181","MAILADDRESS":""},
{"SN":321,"STATE":"Rivers","SURNAME":"Awji","OTHERNAMES":"Inombek Abiante","FEDERALCONSTITUENCY":"Opobo/Nkoro/Andoni","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":322,"STATE":"Rivers","SURNAME":"Randolph","OTHERNAMES":"Oruene Brown","FEDERALCONSTITUENCY":"Degema/Bonny","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":323,"STATE":"Rivers","SURNAME":"Boma","OTHERNAMES":"Godhead","FEDERALCONSTITUENCY":"Akuku-Toru/Asari-Toru","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":324,"STATE":"Rivers","SURNAME":"Jacobson","OTHERNAMES":"Nbima","FEDERALCONSTITUENCY":"Eleme/Oyibo/Tai","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":325,"STATE":"Rivers","SURNAME":"Nsiegbe","OTHERNAMES":"Blessing Ibiba","FEDERALCONSTITUENCY":"Port Harcourt II","PARTY":"PDP","MOBILE":"08033168730","MAILADDRESS":""},
{"SN":326,"STATE":"Rivers","SURNAME":"Eke","OTHERNAMES":"Jerome Amadi","FEDERALCONSTITUENCY":"Etche/Omuma","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":327,"STATE":"Rivers","SURNAME":"Ogundu","OTHERNAMES":"Chinda Kingsley","FEDERALCONSTITUENCY":"Obio/Akpor","PARTY":"PDP","MOBILE":"08033108452","MAILADDRESS":""},
{"SN":328,"STATE":"Rivers","SURNAME":"Dumna","OTHERNAMES":"Mene Ranson Dekor","FEDERALCONSTITUENCY":"Gokana/Khana","PARTY":"PDP","MOBILE":"08034009637","MAILADDRESS":"drdekor68@gmail.com"},
{"SN":329,"STATE":"Rivers","SURNAME":"Tamuno","OTHERNAMES":"Gogo Bright","FEDERALCONSTITUENCY":"Okrika/Ogu/Bolo","PARTY":"PDP","MOBILE":"08035879680/08077166300","MAILADDRESS":""},
{"SN":330,"STATE":"Rivers","SURNAME":"Emekengwa","OTHERNAMES":"Boniface Sunday","FEDERALCONSTITUENCY":"Ikwerre/Emoha","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":331,"STATE":"Sokoto","SURNAME":"Abdullahi","OTHERNAMES":"Balarabe Salame","FEDERALCONSTITUENCY":"Illela/Gwadabawa","PARTY":"APC","MOBILE":"08056897161/08036067910","MAILADDRESS":""},
{"SN":332,"STATE":"Sokoto","SURNAME":"Achida","OTHERNAMES":"Kabiru Marafa","FEDERALCONSTITUENCY":"Wurno/Rahah/Gandi","PARTY":"APC","MOBILE":"08053915071","MAILADDRESS":""},
{"SN":333,"STATE":"Sokoto","SURNAME":"Adar","OTHERNAMES":"Musa Sarkin","FEDERALCONSTITUENCY":"Goronyo/Gada","PARTY":"APC","MOBILE":"08033146526","MAILADDRESS":""},
{"SN":334,"STATE":"Sokoto","SURNAME":"Aliyu","OTHERNAMES":"Shehu .A.","FEDERALCONSTITUENCY":"D/Shuni/Bodings/Tureta","PARTY":"APC","MOBILE":"08030801733/08093196690","MAILADDRESS":""},
{"SN":335,"STATE":"Sokoto","SURNAME":"Bashir","OTHERNAMES":"Isah Salihu","FEDERALCONSTITUENCY":"Tangaza/Gudu","PARTY":"APC","MOBILE":"08035602194/08050398800","MAILADDRESS":"0"},
{"SN":336,"STATE":"Sokoto","SURNAME":"Hassan","OTHERNAMES":"Salla Abubukar III","FEDERALCONSTITUENCY":"Sokoto North/South","PARTY":"APC","MOBILE":"08036179414","MAILADDRESS":"hassandbabubakar@yahoo. com"},
{"SN":337,"STATE":"Sokoto","SURNAME":"Isa","OTHERNAMES":"Aminu Sani","FEDERALCONSTITUENCY":"Isa/S.Birni","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":338,"STATE":"Sokoto","SURNAME":"Nabunkari","OTHERNAMES":"Sa’ad Mohammed","FEDERALCONSTITUENCY":"Binji/Silame","PARTY":"APC","MOBILE":"08037597339","MAILADDRESS":""},
{"SN":339,"STATE":"Sokoto","SURNAME":"Shagari","OTHERNAMES":"Aminu Shehu","FEDERALCONSTITUENCY":"Yabo/Shagari","PARTY":"APC","MOBILE":"08089999522/08037871000","MAILADDRESS":"aminushagary@yahoo.com"},
{"SN":340,"STATE":"Sokoto","SURNAME":"Dasuki","OTHERNAMES":"Abdusamad","FEDERALCONSTITUENCY":"Kebbe/Tambunwal","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":341,"STATE":"Sokoto","SURNAME":"Wamako","OTHERNAMES":"Abdullahi Muhammad","FEDERALCONSTITUENCY":"Kware/Wamakko","PARTY":"APC","MOBILE":"07030998352","MAILADDRESS":""},
{"SN":342,"STATE":"Taraba","SURNAME":"Danasabe","OTHERNAMES":"Charles Hosea","FEDERALCONSTITUENCY":"Gashaka/Kurmi/Sardauna","PARTY":"PDP","MOBILE":"08023542938","MAILADDRESS":"hoseadc2000@yahoo.com"},
{"SN":343,"STATE":"Taraba","SURNAME":"Malle","OTHERNAMES":"Aminu Ibrahim","FEDERALCONSTITUENCY":"Jalingo/Yorro/Zing","PARTY":"APC","MOBILE":"08030604620","MAILADDRESS":"aminumalle1969@gmail.com"},
{"SN":344,"STATE":"Taraba","SURNAME":"Garba","OTHERNAMES":"Hamman Julde","FEDERALCONSTITUENCY":"Bali/Gassol","PARTY":"APC","MOBILE":"08033151232","MAILADDRESS":"Garbadede@yahoo.com"},
{"SN":345,"STATE":"Taraba","SURNAME":"Baido","OTHERNAMES":"Danladi Tijos","FEDERALCONSTITUENCY":"Ardokola Lau/K/Lamido","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":346,"STATE":"Taraba","SURNAME":"Danjuma","OTHERNAMES":"Shiddi Usman","FEDERALCONSTITUENCY":"Ibi/Wukari","PARTY":"APGA","MOBILE":"08035880702","MAILADDRESS":"usdanjo@gmail.com"},
{"SN":347,"STATE":"Taraba","SURNAME":"Kwewum","OTHERNAMES":"Rima Shawulu","FEDERALCONSTITUENCY":"Donga/Ussa/Takum","PARTY":"PDP","MOBILE":"","MAILADDRESS":""},
{"SN":348,"STATE":"Yobe","SURNAME":"Ibrahim","OTHERNAMES":"Khadija Bukar Abba","FEDERALCONSTITUENCY":"Damaturu/Gujba/Gulani/ Tarmuwa","PARTY":"APC","MOBILE":"08026503636/08030314124","MAILADDRESS":""},
{"SN":349,"STATE":"Yobe","SURNAME":"Galadima","OTHERNAMES":"Zakariyau","FEDERALCONSTITUENCY":"Bade/Jakusko","PARTY":"APC","MOBILE":"","MAILADDRESS":""},
{"SN":350,"STATE":"Yobe","SURNAME":"Gadaka","OTHERNAMES":"Ismail Ahmed","FEDERALCONSTITUENCY":"Fika/Fune","PARTY":"APC","MOBILE":"08099371333/08034618500","MAILADDRESS":"yarimagidi@yahoo.com"},
{"SN":351,"STATE":"Yobe","SURNAME":"Lawan","OTHERNAMES":"Goni Bukar","FEDERALCONSTITUENCY":"Bursari/Geidam/Yunusari","PARTY":"APC","MOBILE":"07034266171/08136152464","MAILADDRESS":"bugon2007@gmail.com"},
{"SN":352,"STATE":"Yobe","SURNAME":"Yakubu","OTHERNAMES":"Sidi","FEDERALCONSTITUENCY":"Machina/Nguru/Karasuwa/ Yusufari","PARTY":"APC","MOBILE":"08029702415","MAILADDRESS":"karasuwasy@gmail.com"},
{"SN":353,"STATE":"Yobe","SURNAME":"Sabo","OTHERNAMES":"Garba","FEDERALCONSTITUENCY":"Nangere/Potiskum","PARTY":"PDP","MOBILE":"08034433318","MAILADDRESS":"sgarba77@yahoo.com"},
{"SN":354,"STATE":"Zamfara","SURNAME":"Anka","OTHERNAMES":"Lawal , HassanMohammed","FEDERALCONSTITUENCY":"Anka/Talata Mafara","PARTY":"APC","MOBILE":"08068666888","MAILADDRESS":""},
{"SN":355,"STATE":"Zamfara","SURNAME":"Moriki","OTHERNAMES":"Hussaini Abubakar","FEDERALCONSTITUENCY":"Shinkafi/Zurmi","PARTY":"APC","MOBILE":"08036143488","MAILADDRESS":"sardaunanmoriki01@yahoo. com"},
{"SN":356,"STATE":"Zamfara","SURNAME":"Isah","OTHERNAMES":"Ibrahim","FEDERALCONSTITUENCY":"Gusau/Tsafe","PARTY":"APC","MOBILE":"08060030404","MAILADDRESS":"0"},
{"SN":357,"STATE":"Zamfara","SURNAME":"Lawal","OTHERNAMES":"Mu'azu","FEDERALCONSTITUENCY":"Gummi/ Bukkuyum","PARTY":"APC","MOBILE":"08035876329","MAILADDRESS":"muazulawalbtuche@gmail. com"},
{"SN":358,"STATE":"Zamfara","SURNAME":"Gora","OTHERNAMES":"Yahaya Chado","FEDERALCONSTITUENCY":"Bakura/Maradun","PARTY":"APC","MOBILE":"08035075560","MAILADDRESS":""},
{"SN":359,"STATE":"Zamfara","SURNAME":"Doruwa","OTHERNAMES":"Sani Ibrahim Ruwan","FEDERALCONSTITUENCY":"Bungudu/Maru","PARTY":"APC","MOBILE":"08022076777","MAILADDRESS":""}]
